version: "3.3"
services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    environment:
      - PUBLICHOST=ftp
      - FTP_USER_NAME=ftp
      - FTP_USER_PASS=ftp
      - FTP_USER_HOME=/var/www
    ports:
      - 30000-30009:30000-30009
      - target: 21
        published: 21
        protocol: tcp
    volumes:
      # Dev
      - ../src:/var/www
