version: "3.3"
services:
    php:
      image: greg0/php-runtime-env:php${PHP_VERSION}-dev
      volumes:
        # Dev
        - ../src:/var/www
        - ../images/php-config/php.ini:/usr/local/etc/php/conf.d/docker-php-project.ini
